In [4]:
#padas 설치는 최초 1회만! 그러나 import는 매번 실행 필요!
import pandas as pd

In [5]:
df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
#특정 컬럼 데이터만 조회하기
df[['국어']]

#이름, 국어 컬럼  (컬럼 조회 시 컬럼명을 리스트 형태로 설정해야한다!)
df[['이름', '국어']]

     국어
0  90.0
1  78.0
2   NaN
3  33.0
4   0.0
5   NaN
6  90.0
7  78.0
8   NaN
9  86.0

In [28]:
#특정 열과 행 데이터 조회
#1. df.loc[행 번호, 열 이름] / 이름으로 조회하겠다!
#2. df.iloc[행 번호, 열 번호(index)] / 순번으로 조회하겠당!

df.loc[2]       # 2번행 전체 열 데이터 조회
df.loc[1 : 4]   # 1~4번행 열 데이터 조회
df.loc[1 : ]    # 1행부터 전체 열 데이터 조회

df.loc[0, '이름']   # 0번행 '이름' 데이터 조회
df.loc[0, ['이름']]
df.loc[1 : 4, ['이름', '성별']] # 1~4번행, [이름, 성별] 데이터 조회

df.iloc[1 : 3, [0, 2]]  # 1~3번행, [0, 2]번 컬럼 데이터 조회
df.iloc[ : , 1 : 5]

    이름 성별    국어     수학
0  구이서  남  90.0   89.0
1  김이정  여  78.0   45.0
2  오지수  남   NaN    NaN
3  김선후  남  33.0   44.0
4  하진희  여   0.0   85.0
5  강현진  남   NaN    NaN
6  김진솔  남  90.0   89.0
7  박서준  여  78.0   45.0
8  김성희  남   NaN    NaN
9  이지서  여  86.0  100.0

In [ ]:
# 특정 조건에 만족하는 데이터 조회
# 국어 점수가 80점 이상인 데이터만 조회

#1. 국어점수가 80점 이상이라는 조건
df['국어'] >= 80

#2. 만든 조건을 적용하는 코드 (전체 컬럼 조회)
df[ df['국어'] >= 80 ]

# 위와 같은 코드를 loc를 사용 (컬럼의 조건도 추가 가능!)
df.loc[ df['국어'] >= 80 ]   #국어를 기준으로 행을 조회하는 것! =  조건을 행 조건에 넣어야한당!

# 성별이 '여'인 데이터만 조회
df[ df['성별'] == '여']
df.loc[df['성별'] == '여', ['이름', '성별']]
df.iloc[df['성별'] == '여' , 0 : 3]

# 국어가 80점 이상이면서 성별은 여인 학생만 조회
conditon1 = df['국어'] >= 80 
conditon2 = df['성별'] == '여'

df[conditon1 & conditon2] # and
df[conditon1 | conditon2] # or
# 여러개의 조건을 직접 작성하려면 조건마다 무조건 소괄호에 감싸야한다.
df[(df['국어'] >= 80) & (df['성별'] == '여')]
df.loc[conditon1 & conditon2]


# 팁)  조건에 맞는 데이터 조회 시 query() 함수를 사용할 수 있음
#df.query('국어 >= 80')
#df.query(' 이름 == "구이서" ')
df.query(' 국어 >= 80 and 성별 == "여" ')

    반   이름 성별    국어     수학 응시여부 확인여부
9  B반  이지서  여  86.0  100.0   응시   확인