### 결측치
##### 측정되지 않은 데이터를 삭제할지, 특정 값으로 바꿀지 선택해서 데이터셋에서 측정되지 않는 값을 없애는 단계
##### 결측치는 NA, NaN로 표현된다.
##### 결측치 처리는 머신러닝 학습 전 단계에서 반드시 진행되어야 함.

###### 학습시키고자하는 목적에 따라 결측치를 제거하거나, 특정 값으로 변경할지 결정해야 한다.
###### 처리 방법을 우리가 현 단계에서 많이 배울 수 없다...ㅠㅠ
###### 어떻게 처리할지는 AI를 활용해서 결정!

In [11]:
import pandas as pd

df = pd.read_excel("data.xlsx")
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 데이터셋에서 결측치가 존재하는지 확인하는 코드
df.isnull() #각 행과 열 데이터를 결측치 여부에 따라 true, false로 표현

# 실제 결측치 존재 여부는 아래 코드로 확인
# 각 컬럼의 결측치 수의 합을 출력
df.isnull().sum()

반       0
이름      0
성별      0
국어      3
수학      3
응시여부    2
확인여부    3
dtype: int64

In [ ]:
# 결측치 제거(결측치가 포함된 행 또는 컬럼 전체를 삭제)
# df.dropna(axis='index', how='any', subset=['컬럼명'])
# axis : 행과 열 중 무엇을 삭제할 지 지정
# axis = 'index', axis = 0      -> 결측치가 있는 행을 지우겠다. (default)
# axis = 'columns', axis = 1    -> 결측치가 있는 열을 지우겠다.
# how = 'any'         -> 결측치가 하나라도 존재하면 삭제 (default)
# how = 'all'         -> 모든 데이터가 결측치라면 삭제
# subset = ['컬럼명'] -> 결측치를 삭제할 특정 컬럼을 지정
# ----------위 세 매개변수는 필요할 때만 작성----------

In [ ]:
#결측치가 존재하는 행을 삭제
df.dropna()  #결측치가 제거되지만, 제거된 결과를 저장하지 않는다.    #axis = 'index', how = 'any' default!!

df.dropna(inplace=True) # 결측치가 제거가 저장되지만, 원본 데이터를 유지 불가.
new_df = df.dropna()    #추천하는 방식 = 새로운 변수 선언 및 저장

In [ ]:
# 결측치가 하나라도 존재하는 열을 제거
second_df = df.dropna(axis='columns')    #any 기본값.
second_df

    반   이름 성별
0  A반  구이서  남
1  B반  김이정  여
2  A반  오지수  남
3  B반  김선후  남
4  A반  하진희  여
5  A반  강현진  남
6  B반  김진솔  남
7  B반  박서준  여
8  A반  김성희  남
9  B반  이지서  여

In [ ]:
# 행 전체가 결측치인 행을 삭제하는 코드
df.dropna(how='all')

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 결측치가 하나라도 존재하는 행을 삭제하는 코드
df.dropna(axis='index', how='any')

In [ ]:
# ['응시여부']컬럼을 기준으로 결측치가 존재하는 행을 삭제하는 코드
df.dropna(subset=['응시여부'])

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 결측체를 다른 값으로 변경하기

#모든 결측치를 0으로 채움
#df.fillna(0)   #저장되지 않음
#df.fillna(0, inplace=True)  #저장, 원본 데이터가 변화\
new_df = df.fillna(0)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 컬럼별 결측치 데이터 채우기
df.fillna({'수학' : 0, '응시여부' : '미응시'})

# '국어' 컬럼의 결측치를 국어의 평균으로 채우기
df.fillna( {'국어' : df['국어'].mean()} )

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남  65.0    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남  65.0    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남  65.0    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인