In [1]:
import pandas as pd
df = pd.read_excel("data.xlsx")
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 데이터 변환 replace()
# replace 사용 후 결과를 저장하려면 inplace=True 매개변수 추가 or 다른 변수에 저장

# 모든 데이터(컬럼 구분 없이)에서 '응시' 문자열을 'Y'로 변경    / ex) 김응시가 있으면 김Y로 바뀐다;;

df.replace('응시', 'Y')
df

# 모든 데이터(컬럼 구분 없이)에서 '남', '여' 문자열을 변경
df.replace( {'남' : 'male', '여' : 'female'} )

# 특정 컬럼의 값을 변경
new_dfY = df['확인여부'].replace('확인', '1')
df

0      1
1      1
2      1
3    NaN
4    NaN
5    NaN
6      1
7      1
8      1
9      1
Name: 확인여부, dtype: str

In [ ]:
# 컬럼 추가    -> 데이터의 구조 변화(컬럼의 추가) :  inplace = True xxx  -> 자동저장 / 데이터의 내용 변화(컬럼, 행의 내용 변화, 함수() 사용) -> commit 필요!

# 총점 컬럼 추가 및 데이터(국어+수학 합)
df['총점'] = df['국어'] + df['수학']
df

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [ ]:
# 컬럼 추가, assign() 함수 사용
# assign() 함수는 컬럼 추가한 결과를 반환해준다. =  원본은 유지하면서, 컬럼이 추가된 데이터셋을 사용할 수 있다.

# 평균 컬럼 추가
new_df = df.assign(평균= df['총점']/2)
new_df      # 평균 컬럼 있다.
df          # 평균 컬럼 없다.

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [ ]:
# 데이터 삭제 drop(), inplace=True or 다른 변수에 저장
#axis='index', axis = 0   => 행 삭제
#axis='columns', axis = 1 => 열 삭제

#'총점' 컬럼 삭제
df.drop(['총점'], axis='columns')   

#'국어' , '수학' 컬럼 삭제
df.drop(['국어', '수학'], axis='columns')

# [0, 1]번째 행 삭제
df.drop([0, 1], axis='index')
#[2]번째 행 삭제
df.drop([2], axis=0)

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0