In [1]:
import pickle
import pandas as pd

In [3]:
#저장한 파일들 불러오기

#인코딩 객체
le = None

#학습된 랜덤포레스트 모델
rf_model = None

#학습에 사용된 컬럼 정보
train_col = None

with open('le_시도명.pkl', 'rb') as f :
  le = pickle.load(f)

with open('rf_model.pkl', 'rb') as f :
  rf_model = pickle.load(f)
  
with open('train_col.pkl', 'rb') as f :
  train_col = pickle.load(f)

In [5]:
train_col

['설비용량(MW)', '기온', '습도', '풍속', 'encoded_시도명']

In [8]:
#예측을 위한 독립변수들
data = {
  '설비용량(MW)' : [295.334], 
  '기온' : [-3],
  '습도' : [24],
  '풍속' : [4.3],
  '시도명' : ['경남'], 
  'encoded_시도명' : 0 
}

#데이터프레임으로 데이터를 변환
df = pd.DataFrame(data)
df

   설비용량(MW)  기온  습도   풍속 시도명  encoded_시도명
0   295.334  -3  24  4.3  경남            0

In [ ]:
#원본데이터 유지를 위해 데이터 복사
new_df = df.copy()

#시도명 인코딩
new_df['encoded_시도명'] = le.transform(new_df['시도명'])

#시도명 컬럼 삭제
new_df.drop(columns='시도명', inplace=True)
new_df

   설비용량(MW)  기온  습도   풍속  encoded_시도명
0   295.334  -3  24  4.3            2

In [11]:
#우리가 전달한 데이터로 발전량을 예측
predict_data = rf_model.predict(new_df)

In [14]:
float(predict_data[0])

110.71490000000006